# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet ef database update
  displayName: 'dotnet dotnet ef database update'
  
- script: docker build -t vehiclesapi .
  displayName: 'docker build'         
  
- script: docker tag vehiclesapi altenchallengecontainers.azurecr.io/vehiclesapi:$(Build.BuildNumber)
  displayName: 'docker tag'  
  
- script: docker login https://altenchallengecontainers.azurecr.io -u AltenChallengeContainers -p SIgnOHm5+EWnoupFU5TC77GZOfiUBHkS
  displayName: 'docker login'
  
- script: docker push altenchallengecontainers.azurecr.io/vehiclesapi:$(Build.BuildNumber)
  displayName: 'docker push'
